web: &WEB
  image: checkraiser/canvas-lms-docker
  # build: .
  entrypoint: ./start.sh
  env_file:
    - './.env'
  labels:
    - convox.port.443.protocol=tls
    - convox.health.timeout=60
    - convox.deployment.minimum=10
  ports:
    - 8000:80
    - 8000:443
  volumes:
    - './start.sh:/var/canvas/start.sh'
    - './config/database.yml:/var/canvas/config/database.yml'
    - './config/domain.yml:/var/canvas/config/domain.yml'
    - './config/security.yml:/var/canvas/config/security.yml'
    - './config/canvas.conf:/etc/apache2/sites-enabled/canvas.conf'
  
web-nossl:
  <<: *WEB
  volumes:
    - './start.sh:/var/canvas/start.sh'
    - './config/database.yml:/var/canvas/config/database.yml'
    - './config/domain.yml:/var/canvas/config/domain.yml'
    - './config/security.yml:/var/canvas/config/security.yml'
    - './config/canvas_no_ssl.conf:/etc/apache2/sites-enabled/canvas.conf'

db-initial:
  <<: *WEB
  entrypoint: bundle exec rake db:initial_setup

reset-encryption-key:
  <<: *WEB
  entrypoint: bundle exec rake db:reset_encryption_key_hash

bash:
  <<: *WEB
  entrypoint: /bin/bash
